with-expecter: True
recursive: True
filename: "mock_{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
dir: "{{.InterfaceDir}}/mocks/"
outpkg: "mocks"
all: True
packages:
  go-clean-arch-ddd/template/usecase/interface/in:
    config: {}
  go-clean-arch-ddd/template/usecase/interface/out:
    config: {}