// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockHashTool is an autogenerated mock type for the HashTool type
type MockHashTool struct {
	mock.Mock
}

type MockHashTool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHashTool) EXPECT() *MockHashTool_Expecter {
	return &MockHashTool_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function with given fields: password
func (_m *MockHashTool) Hash(password string) (string, error) {
	ret := _m.Called(password)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHashTool_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockHashTool_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *MockHashTool_Expecter) Hash(password interface{}) *MockHashTool_Hash_Call {
	return &MockHashTool_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *MockHashTool_Hash_Call) Run(run func(password string)) *MockHashTool_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHashTool_Hash_Call) Return(_a0 string, _a1 error) *MockHashTool_Hash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHashTool_Hash_Call) RunAndReturn(run func(string) (string, error)) *MockHashTool_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHashTool creates a new instance of MockHashTool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHashTool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHashTool {
	mock := &MockHashTool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
