// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	register "go-clean-arch-ddd/account/usecase/interface/in/register"

	mock "github.com/stretchr/testify/mock"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: input
func (_m *MockUseCase) Execute(input register.UserRegisterInput) (register.UserRegisterOutput, error) {
	ret := _m.Called(input)

	var r0 register.UserRegisterOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(register.UserRegisterInput) (register.UserRegisterOutput, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(register.UserRegisterInput) register.UserRegisterOutput); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(register.UserRegisterOutput)
	}

	if rf, ok := ret.Get(1).(func(register.UserRegisterInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - input register.UserRegisterInput
func (_e *MockUseCase_Expecter) Execute(input interface{}) *MockUseCase_Execute_Call {
	return &MockUseCase_Execute_Call{Call: _e.mock.On("Execute", input)}
}

func (_c *MockUseCase_Execute_Call) Run(run func(input register.UserRegisterInput)) *MockUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(register.UserRegisterInput))
	})
	return _c
}

func (_c *MockUseCase_Execute_Call) Return(_a0 register.UserRegisterOutput, _a1 error) *MockUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_Execute_Call) RunAndReturn(run func(register.UserRegisterInput) (register.UserRegisterOutput, error)) *MockUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
